sudo: false

matrix:
  include:
    - language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - cmake-data
            - cmake
            - clang-6.0
            - libstdc++-7-dev
            - gcc-6
            - g++-6
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      before_install:
        - pip install --user cpp-coveralls
      before_script:
        - cd Taylan/dsa/Singly-Linked-List/cpp
      script:
        - cmake -H. -Bbuild
        - cd build
        - cmake --build .
        - ./bin/unit_tests
      after_success:
        - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
