sudo: false

matrix:
  include:
    - language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          before_install:
            - pip install --user cpp-coveralls
            - cd Taylan/dsa/Singly-Linked-List/cpp/
          script:
            - cmake -H. -Bbuild
            - cd build
            - cmake --build .
            - ./bin/unit_tests
          after_success:
            - bash <(curl -s https://codecov.io/bash)
          notifications:
            email: false
